### ISSUE TITLE
bug in bigbench hard tutorial example? 

### ISSUE THREAD

**Issue by linyuhongg** [microsoft/Trace#9] opened 2024-08-20 07:21 UTC
The tutorial example at https://microsoft.github.io/Trace/examples/nlp/bigbench_hard.html seem to contain two bugs (one being more of a typo because it does not affect the training):

1. The optimizer registers twice the prompt as parameters to be optimized
```python
optimizer = OptoPrime(dp.parameters() + [dp.prompt_template], config_list=autogen.config_list_from_json("OAI_CONFIG_LIST"))
```

2. In the model architecture, the model is called with `prompt_template.format(question)` inside the bundled layer `create_prompt`. The problem is that `.format` is a function call and thus the `ParameterNode` is recorded as a intermediate node instead of a root node. Why is that a problem? it seems that the opto optimizer only optimizes `ParameterNode` that are root node, as a result, instead of recording the prompt_template inside the graph as the `ParameterNode` it records it `question` (which is a root node) as the variable inside `self.prompt_template`.

One could potentially fix 2 by defining the prompt as a str instead of `ParameterNode` directly inside the bundled function

**Comment by windweller** [comment] 2024-08-20 11:23
Hi @linyuhongg, thanks for raising this issue!

To point 1, nice catch -- the code was first written with an older version of the library. This part will be fixed.

To point 2, I'm not sure I fully understand. Can you run the following code:

```python
task = "sports_understanding"
train = load_dataset("maveriq/bigbenchhard", task)["train"]
examples = [{"question": r["input"], "answer": r["target"]} for r in train]

dp = Predict()
optimizer = OptoPrime(dp.parameters(),
                                    config_list=autogen.config_list_from_json("OAI_CONFIG_LIST"))

GRAPH.clear()
response = dp.forward(examples[0]['question'])
response.backward("success", visualize=True)
```

I think `prompt_template` is still a root node. 

![image](https://github.com/user-attachments/assets/a568f87d-9322-40a4-8be8-c31d93746778)

**Comment by linyuhongg** [comment] 2024-08-20 14:05
I think the problem steems from the fact that `response.backward("success", visualize=True)` builds a different `TraceGraph` than the optimizer `TraceGraph`

**Comment by windweller** [comment] 2024-08-22 01:06
Hi @linyuhongg, thanks for attaching the output! 

If you look at the `#Others`, it starts with `(str) eval0 = ...`, this is actually the output of `create_prompt` -- a system prompt that has the correct question filled in, not the original system prompt that should be optimized.

I wonder if you error is caused by not running this with the new `optimizer = OptoPrime(dp.parameters())`, because after running this code:
```python
task = "sports_understanding"
train = load_dataset("maveriq/bigbenchhard", task)["train"]
examples = [{"question": r["input"], "answer": r["target"]} for r in train]

dp = Predict()
optimizer = OptoPrime(dp.parameters(),
                                    config_list=autogen.config_list_from_json("OAI_CONFIG_LIST"))

for step, example in enumerate(examples):
    GRAPH.clear()
    response = dp.forward(example['question'])
    correctness = eval_metric(example['answer'], response)

    feedback = "correct"

    optimizer.zero_feedback()
    optimizer.backward(response, feedback)

    optimizer.step(verbose=True)
    break
```

I get:

```
#Instruction
You need to change the <value> of the variables in #Variables to improve the output in accordance to #Feedback.

#Code
eval0 = eval(self=ModelWrapper0, prompt_template=str3, question=str0, __code=__code1)
LLMCallable.call_llm0 = LLMCallable.call_llm(self=ModelWrapper1, user_prompt=eval0)
eval1 = eval(self=ModelWrapper2, prompt_template=str3, question=str1, response=LLMCallable.call_llm0, __code=__code0)

#Documentation
[eval] This operator eval(__code, *args, **kwargs) evaluates the code block, where __code is the code (str) and *args and **kwargs are the arguments of the function. The output is the result of the evaluation, i.e., __code(*args, **kwargs).
[LLMCallable.call_llm] .

#Variables
(str) str3=
Given the fields `question`, produce the fields `answer`.

---

Follow the following format.

Question: 
Answer: 

---
Question: {}
Answer:

(code) __code1:def create_prompt(self, prompt_template, question):
        return prompt_template.format(question)
(code) __code0:def extract_answer(self, prompt_template, question, response):
        answer = response.split("Answer:")[1].strip()
        return answer

#Constraints
(code) __code1: The code should start with:
def create_prompt(self, prompt_template, question):
(code) __code0: The code should start with:
def extract_answer(self, prompt_template, question, response):

#Inputs
(ModelWrapper) ModelWrapper2=<opto.trace.modules.model.<locals>.ModelWrapper object at 0x158760220>
(str) str1=Is the following sentence plausible? "Elias Lindholm beat the buzzer."
(ModelWrapper) ModelWrapper1=<opto.trace.modules.model.<locals>.ModelWrapper object at 0x158760220>
(ModelWrapper) ModelWrapper0=<opto.trace.modules.model.<locals>.ModelWrapper object at 0x158760220>
(str) str0=Is the following sentence plausible? "Elias Lindholm beat the buzzer."

#Others
(str) eval0=
Given the fields `question`, produce the fields `answer`.

---

Follow the following format.

Question: 
Answer: 

---
Question: Is the following sentence plausible? "Elias Lindholm beat the buzzer."
Answer:

(str) LLMCallable.call_llm0=Question: Is the following sentence plausible? "Elias Lindholm beat the buzzer."
Answer: Yes, the sentence is plausible. In the context of sports, "beat the buzzer" typically means that an athlete, such as Elias Lindholm, scored right before the time expired in a period or game.

#Outputs
(str) eval1=Yes, the sentence is plausible. In the context of sports, "beat the buzzer" typically means that an athlete, such as Elias Lindholm, scored right before the time expired in a period or game.

#Feedback
correct
```

**Comment by windweller** [comment] 2024-08-22 01:22
Hi @linyuhongg, thanks for attaching the output!

If you look at the #Others, it starts with (str) eval0 = ..., this is actually the output of create_prompt -- a system prompt that has the correct question filled in, not the original system prompt that should be optimized.

I was able to recreate your bug! It's caused by:

```python
@model
class A:
  def __init__(self):
    self.text = ""
    self.text = ParameterNode(self.text, trainable=True)
```

I pushed a fix for the BBH example. So if you do:

```python
prompt_template = dedent("...")
        self.prompt_template = ParameterNode(prompt_template, trainable=True,
                                             description="...")
```

It will work fine.

We are working on a solution to fix the deeper bug. Thanks for pointing this out!

**Comment by windweller** [comment] 2024-08-22 03:16
I updated my comment and found the bug!! Sorry about the wait. Let me know if you see the correct outputs!

**Comment by linyuhongg** [comment] 2024-08-24 07:45
removing `GRAPH.clear()` fixes the solutions for me. 

If I understand correctly: the class initialization automatically register its nodes into the `GRAPH`. Upon clearing the `GRAPH`, the forward pass recreates intermediate nodes during the `forward` and registers them, since initial node `prompt_template` is only declared in during initialization, it is never registered again in the `GRAPH`.

**Comment by windweller** [comment] 2024-08-26 04:00
Yes, your understanding is correct. I thought about adding some patching to the optimizer to address this partially, but right now, it's better to treat the `py_name` of each node as unique and don't call `GRAPH.clear()` after nodes are initialized.

**Closed by windweller** 2024-08-26 04:00 UTC
